name: CI

on: 
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Releasing version ${{ github.event.release.name }}!
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: 'manifest.json'
      env:
        version: ${{ github.event.release.name }}
    - name: Create zip file
      run: |
        zip -ur deezer_${{ github.event.release.name }}.zip css,
        zip -ur deezer_${{ github.event.release.name }}.zip imgs,
        zip -ur deezer_${{ github.event.release.name }}.zip _locales,
        zip -ur deezer_${{ github.event.release.name }}.zip scripts
    - name: Upload Chrome Extension Webstore artifact
      uses: actions/upload-artifact@v1
      with:
        path: deezer_${{ github.event.release.name }}.zip
        
        
