name: CI

on [release]:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world ${{ github.event.release.name }} !
    - name: Run a multi-line script
      run: |
        echo ${{ github.event_name }},
        echo ${{ github.event }},
        echo ${{ github.event.action }},
        echo ${{ github.event.release }},
        echo ${{ github.event.release.name }}
